# Generated by Django 2.2.2 on 2019-06-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('from_account', models.CharField(max_length=10)),
                ('transaction_amount', models.FloatField()),
                ('beneficiary_account', models.CharField(max_length=10)),
                ('beneficiary_name', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
