# Generated by Django 2.2.2 on 2019-06-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_wallet', '0002_auto_20190626_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('CHEQUE', 'cheque'), ('NET BANKING', 'net banking transfer')], default='NET BANKING', max_length=11),
        ),
        migrations.AddField(
            model_name='transaction',
            name='particulars',
            field=models.CharField(default='NET BANKING', max_length=7),
            preserve_default=False,
        ),
    ]
